#!/usr/bin/env python
"""Build Gephi-ready node and edge tables for FT-ICR DOM PMD networks."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


VK_COLORS = {
    "Lipids": "#1B9E77",
    "Carbohydrates": "#E7298A",
    "Aliphatic": "#D95F02",
    "Unsaturated": "#66A61E",
    "Lignin": "#7570B3",
    "Aromatic": "#E6AB02",
    "Tannin": "#A6761D",
    "Other": "#666666",
    "Others": "#666666",
}
VALID_GROUPS = {"CHO", "CHON", "CHONS", "CHOS"}
GROUP_COLORS = {
    "CHO": "#EF0000",
    "CHON": "#336699",
    "CHONS": "#FEC211",
    "CHOS": "#3BC371",
    "Others": "#666699",
}
REACTION_LABELS = {
    "1-C3H6": "1-CH",
    "1-C3H4": "1-CH",
    "1-C2H4": "1-CH",
    "1-C2H2": "1-CH",
    "1-CH2": "1-CH",
    "1-C": "1-CH",
    "1-H2": "1-CH",
    "1+H2": "1+CH",
    "1-CO": "1-CHO",
    "1-CO2": "1-CHO",
    "1-C2H2O2": "1-CHO",
    "1-CH4O": "1-CHO",
    "1-C6H8O6": "1-CHO",
    "1+C6H8O6": "1+CHO",
    "1+C2H2O": "1+CHO",
    "1+O": "1+CHO",
    "1-H2+O": "1+CHO",
    "1+H2O": "1+CHO",
    "1+O2": "1+CHO",
    "1-H2+O2": "1+CHO",
    "1-NH": "1-CHON",
    "1-NH+O": "1-CHON",
    "1-C2H5N": "1-CHON",
    "1-CHON": "1-CHON",
    "1+NH": "1+CHON",
    "1-O+NH": "1+CHON",
    "1-O+NH3": "1+CHON",
    "1-H+NO": "1+CHON",
    "1-H+NO2": "1+CHON",
    "1-SO2": "1-CHOS",
    "1-SO3": "1-CHOS",
    "1+SO3": "1+CHOS",
}
EDGE_COLORS = {
    "1-CH": "#777777",
    "1+CH": "#A6A6A6",
    "1-CHO": "#3B5F21",
    "1+CHO": "#ACD78E",
    "1-CHON": "#843F0B",
    "1+CHON": "#91ACE0",
    "1-CHOS": "#B58B02",
    "1+CHOS": "#FED961",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create Gephi-ready nodes and labeled edges from PMD outputs."
    )
    parser.add_argument(
        "input_dir",
        help=(
            "Processed directory containing network_edge*.csv and "
            "network_formula_matches/network_unique_molecules_*_matched_analysis.xlsx."
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Defaults to input_dir/gephi.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing Gephi output files generated by this script before writing.",
    )
    return parser.parse_args()


def tag_from_matched_path(path: Path) -> str:
    return path.stem.replace("network_unique_molecules_", "").replace("_matched_analysis", "")


def normalize_group(value: object) -> str:
    text = "" if pd.isna(value) else str(value).strip()
    return text if text in VALID_GROUPS else "Others"


def build_node_tables(input_dir: Path, output_dir: Path) -> list[dict[str, object]]:
    matches_dir = input_dir / "network_formula_matches"
    matched_paths = sorted(matches_dir.glob("network_unique_molecules_*_matched_analysis.xlsx"))
    if not matched_paths:
        raise FileNotFoundError(f"No matched molecule tables found in {matches_dir}.")

    summaries: list[dict[str, object]] = []
    for path in matched_paths:
        if path.name.startswith("~$"):
            continue
        tag = tag_from_matched_path(path)
        frame = pd.read_excel(path)
        for column in ["MolForm", "VK", "Group"]:
            if column not in frame.columns:
                raise ValueError(f"{path.name} does not contain {column}.")

        vk_nodes = pd.DataFrame(
            {
                "ID": frame["MolForm"],
                "Label": frame["MolForm"],
                "type": frame["VK"],
            }
        )
        vk_nodes["color"] = vk_nodes["type"].astype(str).map(VK_COLORS).fillna("#666666")
        vk_output = output_dir / f"nodes_{tag}_VK.xlsx"
        vk_nodes.to_excel(vk_output, index=False)

        group_nodes = pd.DataFrame(
            {
                "ID": frame["MolForm"],
                "Label": frame["MolForm"],
                "type": frame["Group"].map(normalize_group),
            }
        )
        group_nodes["color"] = group_nodes["type"].map(GROUP_COLORS).fillna("#666699")
        group_output = output_dir / f"nodes_{tag}_Group.xlsx"
        group_nodes.to_excel(group_output, index=False)

        summaries.append(
            {
                "dataset": tag,
                "nodes": int(len(frame)),
                "vk_nodes": str(vk_output),
                "group_nodes": str(group_output),
            }
        )
    return summaries


def build_edge_tables(input_dir: Path, output_dir: Path) -> list[dict[str, object]]:
    edge_paths = sorted(input_dir.glob("network_edge*.csv"))
    if not edge_paths:
        raise FileNotFoundError(f"No network_edge*.csv files found in {input_dir}.")

    summaries: list[dict[str, object]] = []
    for path in edge_paths:
        frame = pd.read_csv(path)
        for column in ["Source", "Target", "Reaction"]:
            if column not in frame.columns:
                raise ValueError(f"{path.name} does not contain {column}.")

        labels = frame["Reaction"].astype("string").str.strip().map(REACTION_LABELS)
        output = frame.copy()
        output["label"] = labels
        output["label2"] = labels
        output["color"] = labels.map(EDGE_COLORS)

        unlabeled = int(output["label"].isna().sum())
        if unlabeled:
            missing = sorted(output.loc[output["label"].isna(), "Reaction"].dropna().unique().tolist())
            raise ValueError(f"{path.name} has {unlabeled} unlabeled reactions: {missing}")

        out_path = output_dir / f"{path.stem}_labeled.xlsx"
        output.to_excel(out_path, index=False)
        summaries.append({"edge": path.stem, "rows": int(len(output)), "output": str(out_path)})
    return summaries


def clean_output_dir(output_dir: Path) -> None:
    patterns = [
        "nodes_*_VK.xlsx",
        "nodes_*_Group.xlsx",
        "network_edge*_labeled.xlsx",
    ]
    for pattern in patterns:
        for path in output_dir.glob(pattern):
            if path.is_file():
                path.unlink()


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir) if args.output_dir else input_dir / "gephi"
    output_dir.mkdir(parents=True, exist_ok=True)
    if args.clean:
        clean_output_dir(output_dir)

    node_summary = build_node_tables(input_dir, output_dir)
    edge_summary = build_edge_tables(input_dir, output_dir)
    for item in node_summary:
        print(f"{item['dataset']}: {item['nodes']} nodes")
    for item in edge_summary:
        print(f"{item['edge']}: {item['rows']} edges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
